### ISSUE TITLE
Upstream repository gone

### ISSUE THREAD

**Issue by Anthchirp** [conda-forge/publish-feedstock#8]
https://bitbucket.org/logg/publish no longer leads anywhere. I was unable to find any public repository for the software. https://pypi.org/project/publish is a different project.

Unless and until we can find the correct upstream repository I would recommend archiving this feedstock.

**Comment by KGHustad** [comment]
I attempted to fix this with https://github.com/conda-forge/publish-feedstock/pull/9 and https://github.com/conda-forge/publish-feedstock/pull/11 . Builds are still failing for some platforms, but I'm hoping it will sort itself out when the conda-forge bot creates new PRs for rebuilding for pypy and Python 3.9.

**Comment by KGHustad** [comment]
I've exported the old Mercurial repo to git and created a new upstream at https://github.com/doconce/publish/
